version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    environment:
      - ENV=development
      - DATABASE_URL=sqlite:///app/database.db
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: sqlite:latest
    volumes:
      - db_data:/data/db

volumes:
  db_data: